sekce "co je to Python"
Czechitas-Python/uvod-do-progr-1 pull request #83
Opened 2024-01-27 16:46 UTC by JakubDotPy

Přidána sekce "co je to Python" kde je popsáno, co by si začátečník pod pojmem "ten Python" mohl představit. Také se tam snažím srozumitelně vysvětlit, co je to "interpreter".

Snad jsem správně upravil ymls.
Příjmám návrhy na změny v textu.

2024-01-27 16:51 UTC, pesikj approved these changes

2024-01-28 19:45 UTC, ZelenyMartin requested changes

2024-01-28 19:45 UTC, ZelenyMartin commented on priprava/programovani/copatoje-python.md
> +To je ten "program", který jste si stáhli a nainstalovali ze stránek `python.org`.
```suggestion
To je ten "program", který jste si stáhli a nainstalovali ze stránek [python.org](https://www.python.org). 
```

2024-01-28 19:45 UTC, ZelenyMartin commented on priprava/programovani/copatoje-python.md
> +Těmto "kopiím hlavních interpreterů" se říká `virtuální prostředí` a často ho uvidíte pod názvem `venv` nebo `.venv`.
```suggestion
Těmto "kopiím hlavních interpreterů" se říká :term{cs="virtuální prostředí" en="virtual environment"} a často ho uvidíte pod názvem `venv` nebo `.venv`.  
```

2024-01-28 19:45 UTC, ZelenyMartin commented on priprava/programovani/copatoje-python.md
> +Jistě už tušíte, že `Python` je programovací jazyk a že ho budeme používat pro to, abychom se domluvili s počítačem a dali mu tak instrukce, co po něm budeme chtít vykonat.
```suggestion
Jistě už tušíte, že **Python** je programovací jazyk a že ho budeme používat pro to, abychom se domluvili s počítačem a dali mu tak instrukce, co po něm budeme chtít vykonat.  
```

2024-01-28 19:45 UTC, ZelenyMartin commented on priprava/programovani/copatoje-python.md
> +V následujících lekcích se budeme učit psát programy právě v jazyce `Python` a tyto speciální slova a pravidla si ukážeme.
```suggestion
V následujících lekcích se budeme učit psát programy právě v jazyce _Python_ a tyto speciální slova a pravidla si ukážeme.  
```

2024-01-28 19:45 UTC, ZelenyMartin commented on priprava/programovani/copatoje-python.md
> +Nejprve je potřeba nějaký svůj první soubor (v Pythonu nazývaný `script`, nebo `modul`) vytvořit a napsat do něj příkazy tak, aby jim `Python` rozuměl.
```suggestion
Nejprve je potřeba nějaký svůj první soubor (v Pythonu nazývaný `script`, nebo `modul`) vytvořit a napsat do něj příkazy tak, aby jim _Python_ rozuměl.  
```

2024-01-28 19:45 UTC, ZelenyMartin commented on priprava/programovani/copatoje-python.md
> +My budeme v rámci kurzu používat vývojové prostředí `Visual Studio Code`, které je velmi univerzální a rozšířené.
```suggestion
My budeme v rámci kurzu používat vývojové prostředí _Visual Studio Code_, které je velmi univerzální a rozšířené.
```

2024-01-28 19:45 UTC, ZelenyMartin commented on priprava/programovani/copatoje-python.md
> +Pokud budeme chtít aby počítač vykonal, co jsme mu připravili, budeme potřebovat takzvaný `Python interpreter`.
```suggestion
Pokud budeme chtít aby počítač vykonal, co jsme mu připravili, budeme potřebovat takzvaný **Python interpreter**.  
```

2024-01-28 19:45 UTC, ZelenyMartin commented on priprava/programovani/copatoje-python.md
> +> Hlavní oficiální verze, kterou jste si stáhli je psaná v jazyce `C`. Existuje ale i několik dalších verzí (říkáme jim příchutě) napsaných například v jazyce `Java`, `Ruby`, `Rust` a dalších.
```suggestion
> Hlavní oficiální verze, kterou jste si stáhli je psaná v _jazyce C_. Existuje ale i několik dalších verzí (říkáme jim příchutě) napsaných například v jazyce _Java_, _Ruby_, _Rust_ a dalších.
```

2024-01-28 19:45 UTC, ZelenyMartin commented on priprava/programovani/copatoje-python.md
> +> I přesto, že má Python dva hady jako své logo, název `Python` není inspirován hadem.
```suggestion
> I přesto, že má Python dva hady jako své logo, název _Python_ není inspirován hadem.  
```

2024-01-28 19:45 UTC, ZelenyMartin commented on priprava/programovani/copatoje-python.md
> +> `Python` je pojmenovaný po Britské komediální skupině `Monty Python's Flying Circus`.
```suggestion
> _Python_ je pojmenovaný po Britské komediální skupině _Monty Python's Flying Circus_.
```

2024-01-29 11:39 UTC, ZelenyMartin commented
Já to mergnu, až budu mít čas tak zítra večer. Ten blok citace přes `>` tam asi na kodim nikde nemáme, tak kdyby se to nevykreslilo dobře, tak bych to rovnou upravil.

2024-01-30 20:35 UTC, ZelenyMartin approved these changes

2024-01-30 20:36 UTC, merged